version: "3.8"
services:
  backend:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: vehicledetection
  volumes:
    - D:/data:/data # Mount thư mục trên host (C:/my_data) vào container (/data)
  tty: true # Để container không tự động dừng
  restart: "always" # Update restart policy if needed

  runtime: nvidia
